---
title: "Heatmap"
author: "Nikeisha Caruana"
date: "25 July 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Basic differential expression analysis of a MaxQuant proteinGroups file using Limma. 

Read the raw data, making sure to convert 0's to NA's

```{r}
library(tidyverse)
library(stringr)
library(limma)
library(gplots)
library(ComplexHeatmap)
library(circlize) 
library(stringr)
# Read everything
# Be sure to use na = "0" as you definitely don't want NA's to appear as zeros when averaging.
mq_data <- read_tsv("MT_proteingroups_SL201705.txt",na = "0")
```

```{r}
colnames(mq_data) <- make.names(colnames(mq_data))
lfq_data <- mq_data %>% select(Majority.protein.IDs,contains("LFQ"))

long_lfq_data <- lfq_data %>% gather("sample","intensity",-Majority.protein.IDs)

biorep_names <- str_match(long_lfq_data$sample,"[A-Z]*_[0-9]")[,1]

long_lfq_data$biorep_names <- biorep_names

bioav_lfq_data <- long_lfq_data %>% 
  group_by(Majority.protein.IDs,biorep_names) %>% 
  summarise(intensity = mean(intensity,na.rm = TRUE))

bioav_wide_lfq_data <- bioav_lfq_data %>% spread(biorep_names,intensity)
```

```{r}
sample_data <- str_match( colnames(bioav_wide_lfq_data)[-1], pattern = "([A-Z]*)_([0-9])")[,2:3]
colnames(sample_data) <- c("Tissue","Animal")
sample_data <- data.frame(sample_data)
rownames(sample_data) <- colnames(bioav_wide_lfq_data)[-1]
```

```{r}
filtered_data <- bioav_wide_lfq_data %>% filter(!grepl("CON",Majority.protein.IDs)) %>% filter(!grepl("REV",Majority.protein.IDs))
```

```{r}
info_data <- filtered_data %>% select(Majority.protein.IDs) 
expr_data_raw <- filtered_data %>%  ungroup() %>% select(-Majority.protein.IDs)

# log2 is conventional for differential expression studies. 
expr_data_log2 <- log2(expr_data_raw)

```

```{r}
#matrix of expression data
matrix <- as.matrix(expr_data_log2[,0:24])
rownames(matrix) <- info_data$Majority.protein.IDs
matrix[is.na(matrix)] <- 0

#top expressed proteins - I want to label these on the heatmap
maxapply <- apply(matrix,1,max, na.rm=TRUE)
maxapply <- as.data.frame(maxapply)
maxapply <- subset(maxapply, maxapply > 38)

#My attempt at shortening the row names for the labels, problem is when I do this it doesnt match to the matrix row names (for use in indexes), if I want to change the row names I have to make sure I keep all protein names, not just take the first one for the protein and separate them by some character. 

#rownames(matrix) <- str_match(rownames(matrix),"TRINITY_[A-Z]*[0-9]*_c[0-9]_g[0-9]_i[0-9]::g.[0-9]*::m.[0-9]*")

#for row_anno
indexes <- which(rownames(matrix) %in% rownames(maxapply))
labels <- rownames(matrix)[indexes]

Heatmap(matrix, column_title = "S. lineolata tissue types", show_row_names = FALSE, name = "LFQ values (log2)", heatmap_legend_param = list(at = c(0,15,20,25,30,35,40), labels = c(0,15,20,25,30,35,40)),show_row_dend = FALSE, col = colorRamp2(c(0,15,20,25,30,35,40), c("grey85", "aquamarine","lightskyblue", "cornflowerblue", "blue", "navy","black"))) + rowAnnotation(link = row_anno_link( at = indexes, labels = labels,labels_gp = gpar(fontsize = 10)),annotation_width = unit(5,"cm"))

```


